pr:
- 'main'

pool:
  vmImage: 'windows-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: src/SarifWeb.sln
    configuration: 'Release'

- task: ComponentGovernanceComponentDetection@0
