pr:
- 'main'

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
extends:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
    parameters:
      pool:
        name: 1ES-Shared-Hosted-Pool_Windows-Server-2022
        os: windows
      containers:
        default_windows_container:
          image: 1espipelinesdevpme.azurecr.io/windows/ltsc2022/vse2022:latest
          registry: 1espipelinesdevpme.azurecr.io
          tenantId: PME
          identityType: 1ESPipelineIdentity
        
      stages:
      - stage: build
        jobs:
          - job: build
            templateContext:
              inputs:
              - input: checkout
                repository: self
              outputs:
              - output: pipelineArtifact
                targetPath: $(System.DefaultWorkingDirectory)

            steps:
              - task: UseDotNet@2
                displayName: 'Use .NET Core sdk'
                inputs:
                  packageType: sdk
                  version: 5.0.x
              - task: DotNetCoreCLI@2
                inputs:
                  command: 'build'
                  projects: src/SarifWeb.sln
                  configuration: 'Release'
