pr:
- 'main'

pool:
  vmImage: 'windows-latest'

resources:
  repositories:
    - repository: 1esPipelines
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
extends:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
    parameters:
      pool:
        name: 1ES-Shared-Hosted-Pool_Windows-Server-2022
        os: windows

      stages:
      - stage: build
        jobs:
          - job: build
            templateContext:
              outputs:
              - output: pipelineArtifact
                targetPath: $(System.DefaultWorkingDirectory)
                artifactName: sarif-website

            steps:
              
              - task: DotNetCoreCLI@2
                inputs:
                  command: 'build'
                  projects: src/SarifWeb.sln
                  configuration: 'Release'
